### ISSUE TITLE
Can't create a route with a post request

### ISSUE THREAD

**Issue by tremes** [nodeshift/openshift-rest-client#120]
Doing something like `adminClient.apis.route.v1.ns("my-namespace").routes().post({...})` leads to:
` TypeError: adminClient.apis.route.v1.ns(...).routes(...).post is not a function`

**Comment by lholmquist** [comment]
In the nodeshift library, i'm creating Routes here:  https://github.com/nodeshift/nodeshift/blob/master/lib/routes.js#L31 , so you can use that as a guide

There is a little more explanation here on what things become functions, and what are just objects, https://github.com/nodeshift/nodeshift/blob/master/lib/routes.js#L31

but basically, if in the API there is a path template(thing thing in the curly brackets) like `/apis/apps/v1/namespaces/{namespace}/deployments`, that will translate to a function.  so that would be `client.apis.apps.v1.namespace("namespacename").deployments`

**Comment by tremes** [comment]
Ehm OK :-) Thanks again
